export { HeadEr, headerLink } from './header'
export { ButtOns, buttonLink } from './buttons'
export { ShadowBox, boxLink } from './box'
export {BodyBox, bodyLink } from './body'
export { Footer, footerLink } from './footer'